spring:
  profiles:
    active:
    -dev
---
server:
  port: 8002
spring:
  application:
    name: STUDET-PROVIDER
  profiles:dev
---
server:
  port: 1299
spring:
  application:
    name: STUDET-PROVIDER
  profiles:test #测试环境
